security:
    encoders:
        App\Entity\Usuario:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/busqueda, roles: "ROLE_USER" }
        - { path: ^/sitios, roles: "ROLE_USER" }
        - { path: ^/ajustes, roles: "ROLE_USER" }
        - { path: ^/buscarLugares, roles: "ROLE_USER" }
        - { path: ^/nuevoFavorito, roles: "ROLE_USER" }
        - { path: ^/obtenerFavoritos, roles: "ROLE_USER" }
        - { path: ^/eliminarFavoritos, roles: "ROLE_USER" }
        - { path: ^/cambiarClave, roles: "ROLE_USER" }
        - { path: ^/cambiarEmail, roles: "ROLE_USER" }
        - { path: ^/eliminarUsuario, roles: "ROLE_USER" }
