index:
    path: /
    controller: App\Controller\MainController::index

busqueda:
    path: /busqueda
    controller: App\Controller\MainController::busqueda

sitios:
    path: /sitios
    controller: App\Controller\MainController::sitios

ajustes:
    path: /ajustes
    controller: App\Controller\MainController::ajustes

buscarLugares:
    path: /buscarLugares
    controller: App\Controller\MainController::buscarLugares
    methods: ["POST"]

nuevoFavorito:
    path: /nuevoFavorito
    controller: App\Controller\MainController::nuevoFavorito
    methods: ["POST"]

obtenerFavoritos:
    path: /obtenerFavoritos
    controller: App\Controller\MainController::obtenerFavoritos
    methods: ["GET"]

eliminarFavorito:
    path: /eliminarFavorito/{idSitio}
    controller: App\Controller\MainController::eliminarFavorito
    methods: ["DELETE"]

cambiarClave:
    path: /cambiarClave
    controller: App\Controller\MainController::cambiarClave

eliminarFavoritos:
    path: /eliminarFavoritos
    controller: App\Controller\MainController::eliminarFavoritos
    methods: ["DELETE"]