index:
    path: /
    controller: App\Controller\MainController::index

busqueda:
    path: /busqueda
    controller: App\Controller\MainController::busqueda

sitios:
    path: /sitios
    controller: App\Controller\MainController::sitios

buscarLugares:
    path: /buscarLugares
    controller: App\Controller\MainController::buscarLugares
    methods: ["POST"]